### ISSUE TITLE
Unknown versioncheck response for firmid=FIRM.

### ISSUE THREAD

**Issue by ychromosome** [sedrubal/brother_printer_fwupd#15]
**Description:**

*The update also fails on the web-client. I guess Brother made an error with Firmware "Q" for my MFC-J5625*

**Command:**

```sh
brother_printer_fwupd 
```

**Output:**

```
Discovering printer via MDNS.
Service OKI-MC573-C1BDC1._pdl-datastream._tcp.local. added
Service Brother MFC-J5625DW._pdl-datastream._tcp.local. added
Querying printer info via SNMP.
Detected MFC-J5625DW with following firmware version(s): FIRM@Q2003042157:4BBD
Querying firmware download URL from Brother update API.
Sending POST request to https://firmverup.brother.co.jp/kne_bh7_update_nt_ssl/ifax2.asmx/fileUpdate with following content:

<REQUESTINFO>
    <FIRMUPDATETOOLINFO>
        <FIRMCATEGORY>FIRM</FIRMCATEGORY>
        <OS>LINUX</OS>
        <INSPECTMODE>1</INSPECTMODE>
    </FIRMUPDATETOOLINFO>

    <FIRMUPDATEINFO>
        <MODELINFO>
            <SERIALNO></SERIALNO>
            <NAME>MFC-J5625DW</NAME>
            <SPEC>0203</SPEC>
            <DRIVER></DRIVER>
            <FIRMINFO>
                
        <FIRM>
            <ID>FIRM</ID>
            <VERSION>Q2003042157:4BBD</VERSION>
        </FIRM>
        
            </FIRMINFO>
        </MODELINFO>
        <DRIVERCNT>1</DRIVERCNT>
        <LOGNO>2</LOGNO>
        <ERRBIT></ERRBIT>
        <NEEDRESPONSE>1</NEEDRESPONSE>
    </FIRMUPDATEINFO>
</REQUESTINFO>

Response:
<?xml version="1.0" encoding="UTF-8" ?><RESPONSEINFO><FIRMUPDATEINFO><VERSIONCHECK>2</VERSIONCHECK></FIRMUPDATEINFO></RESPONSEINFO>
Unknown versioncheck response for firmid=FIRM.

```

**Exception:**

```python
Traceback (most recent call last):
  File "/home/martin/.local/lib/python3.11/site-packages/brother_printer_fwupd/__main__.py", line 147, in main
    run()
  File "/home/martin/.local/lib/python3.11/site-packages/brother_printer_fwupd/__main__.py", line 199, in run
    download_url = get_download_url(
                   ^^^^^^^^^^^^^^^^^
  File "/home/martin/.local/lib/python3.11/site-packages/brother_printer_fwupd/firmware_downloader.py", line 81, in get_download_url
    raise ValueError(f"Unknown versioncheck response for firmid={firmid}.")
ValueError: Unknown versioncheck response for firmid=FIRM.

```

**Comment by sedrubal** [comment]
Thanks for the report. I fear we can't do anything if the update also fails with official Brother tools.
