### ISSUE TITLE
ModuleNotFoundError: No module named 'asyncore'

### ISSUE THREAD

**Issue by bwakkie** [sedrubal/brother_printer_fwupd#24]
Hi,

Getting the following error on Manjaro when installing via option C:

My printer allows me to upload firmware via tftp so only downloading the bin would be ok with me too.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/me/source/brother_printer_fwupd/brother_printer_fwupd/__main__.py", line 25, in <module>
    from .snmp_info import get_snmp_info
  File "/home/me/source/brother_printer_fwupd/brother_printer_fwupd/snmp_info.py", line 7, in <module>
    from pysnmp.hlapi import (
  File "/home/me/source/brother_printer_fwupd/.venv/lib/python3.12/site-packages/pysnmp/hlapi/__init__.py", line 10, in <module>
    from pysnmp.hlapi import auth
  File "/home/me/source/brother_printer_fwupd/.venv/lib/python3.12/site-packages/pysnmp/hlapi/auth.py", line 7, in <module>
    from pysnmp.entity import config
  File "/home/me/source/brother_printer_fwupd/.venv/lib/python3.12/site-packages/pysnmp/entity/config.py", line 8, in <module>
    from pysnmp.carrier.asyncore.dgram import udp, udp6, unix
  File "/home/me/source/brother_printer_fwupd/.venv/lib/python3.12/site-packages/pysnmp/carrier/asyncore/dgram/udp.py", line 9, in <module>
    from pysnmp.carrier.asyncore.dgram.base import DgramSocketTransport
  File "/home/me/source/brother_printer_fwupd/.venv/lib/python3.12/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 10, in <module>
    from pysnmp.carrier.asyncore.base import AbstractSocketTransport
  File "/home/me/source/brother_printer_fwupd/.venv/lib/python3.12/site-packages/pysnmp/carrier/asyncore/base.py", line 9, in <module>
    import asyncore
ModuleNotFoundError: No module named 'asyncore'
```

**Comment by jedie** [comment]
Same here :(

```
pipx run brother-printer-fwupd
NOTE: running app 'brother_printer_fwupd' from 'brother-printer-fwupd'
Traceback (most recent call last):
  File "/home/jens/.cache/pipx/e2e9c4be15adfa7/bin/brother_printer_fwupd", line 5, in <module>
    from brother_printer_fwupd.__main__ import main
  File "/home/jens/.cache/pipx/e2e9c4be15adfa7/lib/python3.12/site-packages/brother_printer_fwupd/__main__.py", line 25, in <module>
    from .snmp_info import get_snmp_info
  File "/home/jens/.cache/pipx/e2e9c4be15adfa7/lib/python3.12/site-packages/brother_printer_fwupd/snmp_info.py", line 7, in <module>
    from pysnmp.hlapi import (
  File "/home/jens/.cache/pipx/e2e9c4be15adfa7/lib/python3.12/site-packages/pysnmp/hlapi/__init__.py", line 10, in <module>
    from pysnmp.hlapi import auth
  File "/home/jens/.cache/pipx/e2e9c4be15adfa7/lib/python3.12/site-packages/pysnmp/hlapi/auth.py", line 7, in <module>
    from pysnmp.entity import config
  File "/home/jens/.cache/pipx/e2e9c4be15adfa7/lib/python3.12/site-packages/pysnmp/entity/config.py", line 8, in <module>
    from pysnmp.carrier.asyncore.dgram import udp, udp6, unix
  File "/home/jens/.cache/pipx/e2e9c4be15adfa7/lib/python3.12/site-packages/pysnmp/carrier/asyncore/dgram/udp.py", line 9, in <module>
    from pysnmp.carrier.asyncore.dgram.base import DgramSocketTransport
  File "/home/jens/.cache/pipx/e2e9c4be15adfa7/lib/python3.12/site-packages/pysnmp/carrier/asyncore/dgram/base.py", line 10, in <module>
    from pysnmp.carrier.asyncore.base import AbstractSocketTransport
  File "/home/jens/.cache/pipx/e2e9c4be15adfa7/lib/python3.12/site-packages/pysnmp/carrier/asyncore/base.py", line 9, in <module>
    import asyncore
ModuleNotFoundError: No module named 'asyncore'
```

Think pysnmp is just to old for newer python versions :( Should be updated!

**Comment by sedrubal** [comment]
Sorry for the late reply. I'm wondering, why this happened to you. I thought pipx and poetry are taking care of the dependencies and their versions.

However, you are right and it was time to update the dependencies. Just now, I pushed the new tag [0.8.0](https://github.com/sedrubal/brother_printer_fwupd/releases/tag/0.8.0). I did a big rework of the entire project, moved it from poetry to uv, added unittests and much more. I'd be happy if you could test it again and report back any issues.

Additionally, I published a docker image and added a new method A to the readme which explains how to use it. If you have such issues again, you might want to test the docker image.

I hope this fixes your problems. Otherwise feel free to reopen this issue.
